worked on the reviews
ChainWhiZ/chainwhiz-dapp-v2 pull request #50
Opened 2022-11-06 17:41 UTC by Ladeee

worked on the reviews

2022-11-06 23:22 UTC, Xand6r commented
MOBILE

Use this png for mobile screen homepage bg- https://onedrive.live.com/?authkey=%21ANmfPoEQJmesXd8&cid=FE802492EDD642ED&id=FE802492EDD642ED%213122&parId=FE802492EDD642ED%213103&o=OneUp
Play icon to be changed (mentioned in desktop comment)
Intensity of glow (neon) to be increased in the hero section.
Hero and Ready to level up BG to be blended
Ready to level up para to be aligned with the below cards.
[https://github.com/ChainWhiZ/chainwhiz-dapp-v2/blob/main/pages/home/components/bounty/bounty.module.scss#L16](https://github.com/ChainWhiZ/chainwhiz-dapp-v2/blob/main/__pages__/home/components/bounty/bounty.module.scss#L16)- change the width to 23rem
WHen menu bar is opened. the page behind it seems to behave in a weird way. Please fix it.
MEnu bar needs correction,please connect on call
Our partners and View all bounties gapping is huge.
https://github.com/ChainWhiZ/chainwhiz-dapp-v2/blob/main/__pages__/home/components/partner/partner.module.scss#L12- width:23rem
neon green is distorted behind the 96% card
Your voice... text- increase font-size
lot-->uppercase
how we work--uppercase
width of the latest publication cards to be increased. (23rem)
A team that never stops!---> A team that (one line) never stops(next line)
newsletter-> N caps
gapping to be reduced b/w wisescribe and team section
from wisescribe until footer bg color change--#100c1a
Enter you email input width to be increased(23rem)
footer- chainwhiz and social icon missing
footer menu- font-weight change
use this for footer bg- https://onedrive.live.com/?authkey=%21ANmfPoEQJmesXd8&cid=FE802492EDD642ED&id=FE802492EDD642ED%213168&parId=FE802492EDD642ED%213103&o=OneUp

2022-11-12 13:47 UTC, rajashree23 commented
@Ladeee 
yarn build is failing for this branch, could you please check?
and also, I see some reviews aren't addressed yet especially the ones with the color codes

2022-11-12 13:59 UTC, Xand6r commented
@rajashree23 can you pull and try again. not sure why but i can build on my end.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/38471362/201477531-a5766d63-7a73-4010-ab2e-3584bbb9a57e.png">

2022-11-12 16:07 UTC, rajashree23 commented
> @rajashree23 can you pull and try again. not sure why but i can build on my end. <img alt="image" width="663" src="https://user-images.githubusercontent.com/38471362/201477531-a5766d63-7a73-4010-ab2e-3584bbb9a57e.png">

i still get it
![image](https://user-images.githubusercontent.com/33730790/201483162-eacd5296-bfba-446d-a892-99b89272ad80.png)

2022-11-12 16:22 UTC, rajashree23 commented
> > @rajashree23 can you pull and try again. not sure why but i can build on my end. <img alt="image" width="663" src="https://user-images.githubusercontent.com/38471362/201477531-a5766d63-7a73-4010-ab2e-3584bbb9a57e.png">
> 
> i still get it ![image](https://user-images.githubusercontent.com/33730790/201483162-eacd5296-bfba-446d-a892-99b89272ad80.png)

for now i have fixed the path name and reviewing it

2022-11-13 08:18 UTC, rajashree23 commented
Desktop

- [ ] ![image](https://user-images.githubusercontent.com/33730790/201512388-a2ab1d5f-a6ef-4144-8220-dd63fd1814ab.png)
 BG helix pattern for Class meets class to be shifted down.
- [ ] Got a Minute, Sneak peek - font weight to be reduced. (Try Poppins Regular)
- [ ] Enter your email label to be increased in opacity(placeholder color is different than design)
- [ ] Our Torchbearers Glow intensity is to be increased
- [ ] Create Solve Repeat white glow to be shifted up. The neon green on the illustration is to be shifted right.
- [ ] Article titles font weight to be reduced. Try Poppins regular
- [ ] A team that never stops neon green glow intensity to be reduced. White glow radius to be reduced on the right.
- [ ] Team members name, description font weight to be reduced
- [ ] Team member circle to popup on hover.
- [ ] Footer section Enter your email label to be increased in opacity.
- [ ] Say Hi!,  to be right aligned.
- [ ]  ![image](https://user-images.githubusercontent.com/33730790/201512507-7c0f9ca7-e85a-4534-bd70-d0b53473c9e3.png)
icon missing in button

2022-11-13 08:20 UTC, rajashree23 commented
Mobile

- [ ] Menubar isn't completed as per our last call discussions. (glow and margin-top)
- [ ] Card statistics(Jaw dropping cards) to be increased width-wise. (372px)
- [ ] How we Work, letter spacing to be reduced. Refer Design.
- [ ] Illustration white glow to be removed.
- [ ] You're welcome to be in one-line.(Publication section)
- [ ] A team that never stops neon green glow to be reduced.
- [ ] Team that never stops slider to be changing after 5 seconds( can do in this PR or maybe create issue and do later)
- [ ] Say Hi and hello@chainwhiz.app font weight to be reduced.


Rest all looks great :)

2022-11-13 08:26 UTC, rajashree23 commented
@Xand6r it's better to keep one of them as primary font
[L22](https://github.com/ChainWhiZ/chainwhiz-dapp-v2/blob/general-reviews/styles/variables.scss#L22)
[L20](https://github.com/ChainWhiZ/chainwhiz-dapp-v2/blob/general-reviews/styles/variables.scss#L20)

2022-11-13 08:26 UTC, rajashree23 requested changes

2022-11-13 08:26 UTC, rajashree23 commented on components/navbar/index.tsx
> +import Dropdown from './dropdown';
Please change it to the exact file path cause build is failing for me

2022-11-15 16:32 UTC, rajashree23 commented
all looks great!
have conveyed three changes to Trust  and then we are good to go!

2022-11-15 22:09 UTC, Xand6r commented
awesome! 🚀

2022-11-16 16:53 UTC, rajashree23 approved these changes
Looks good to me!(made small changes.)

2022-11-19 08:42 UTC, Xand6r approved these changes
LGTM

2022-11-19 08:42 UTC, merged